### ISSUE TITLE
Use twig blocks for form rendering

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataUserBundle#784]
We should replace all `<form>` elements in the twig templates with the twig function `form_start` and `form_end`. We should also move the `action` and `method` (POST, GET) attribute to the PHP files.

This would decouples the business logic from the layout.
## Todo

The following files contains form elements.
- [ ] https://github.com/sonata-project/SonataUserBundle/blob/3.x/Resources/views/Security/login.html.twig
- [ ] https://github.com/sonata-project/SonataUserBundle/blob/3.x/Resources/views/Admin/Security/two_step_form.html.twig
- [ ] https://github.com/sonata-project/SonataUserBundle/blob/3.x/Resources/views/Resetting/request.html.twig
- [ ] https://github.com/sonata-project/SonataUserBundle/blob/3.x/Resources/views/Resetting/reset.html.twig
- [ ] https://github.com/sonata-project/SonataUserBundle/blob/3.x/Resources/views/Profile/edit_profile_content.html.twig
- [ ] https://github.com/sonata-project/SonataUserBundle/blob/3.x/Resources/views/Profile/edit_authentication_content.html.twig
- [ ] https://github.com/sonata-project/SonataUserBundle/blob/3.x/Resources/views/Registration/register_content.html.twig
- [ ] https://github.com/sonata-project/SonataUserBundle/blob/3.x/Resources/views/Resetting/request_content.html.twig
- [ ] https://github.com/sonata-project/SonataUserBundle/blob/3.x/Resources/views/Security/base_login.html.twig

**Comment by abhinavkumar940** [comment]
Has someone picked this, yet? I would like to work on this.

**Comment by OskarStark** [comment]
feel free to start @abhinavkumar940 👍

**Comment by abhinavkumar940** [comment]
Okay, it looks trickier that I originally thought. I haven't checked them all but the majority looks like overridden FOSUserBundle forms. As, we don't have a Symfony FormView in twig, using `form_start` and `form_end` is not possible.

In a way all these templates are doing is, render the form with their `action` pointed to the FOSUserBundle route. The FOSUserBundle controllers then handles the rest.

What do you suggest?

**Comment by jordisala1991** [comment]
Most of those forms are already gone. The only one that makes sense to migrate to a formType is the reset password request. #1489
